name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.13
  - pip:
    - argparse
    - pandas
    - numpy
    - seaborn
    - matplotlib
    - openpyxl
    - statsmodels
