import os

#### load config ####
if "--configfile" in sys.argv:
    i = sys.argv.index("--configfile")
    config_path = sys.argv[i + 1]
    configfile: config_path
else:
    config_path = "config/config.yml"
    configfile: config_path

ANALYSIS_DIR = config["ANALYSIS_DIR"]
SCRIPTS_DIR  = config["SCRIPTS_DIR"]

_nvi_cfg     = config["NATIVE_VS_IVT"]
_nvi_by_name = {
    row[0]: dict(zip(_nvi_cfg["header"], row))
    for row in _nvi_cfg["data"]
}

def _sanitized(name, side):
    return os.path.join(ANALYSIS_DIR, "sanitized", f"{name}_{side}.bed")


def _coverage_dist_opts(wildcards):
    """Threshold line + x-axis floor, only for the coverage distribution."""
    if wildcards.column != "coverage":
        return ""
    name, side = wildcards.stem.rsplit("_", 1)
    thr = _nvi_by_name[name][f"min_{side}_coverage"]
    return f"--vline {thr} --xmin 1"

# stem -> raw path  (e.g. "polyA_native" -> "raw/polyA_native_merged...bed")
# stem -> sanitized path  (e.g. "polyA_native" -> "analysis/sanitized/polyA_native.bed")
_raw_input_paths = {}
_dist_files      = {}
for _name, _e in _nvi_by_name.items():
    for _side, _key in (("native", "native_path"), ("ivt", "ivt_path")):
        _stem = f"{_name}_{_side}"
        _raw_input_paths[_stem] = _e[_key]
        _dist_files[_stem]      = _sanitized(_name, _side)


include: "rules/samtools.smk"


#### rules ####

rule all:
    input:
        expand(
            os.path.join(ANALYSIS_DIR, "{stem}.{column}_dist.{ext}"),
            stem=_dist_files.keys(),
            column=config["PLOT_COLUMNS"],
            ext=["tsv", "pdf"],
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.bed.gz"),
            name=_nvi_by_name.keys(),
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_pvalue_dist.{ext}"),
            name=_nvi_by_name.keys(),
            ext=["tsv", "pdf"],
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt.{column}_scatter.{ext}"),
            name=_nvi_by_name.keys(),
            column=config["PLOT_COLUMNS"],
            ext=["pdf", "tsv"],
        ),
        os.path.join(ANALYSIS_DIR, "threshold_sweep.pdf"),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_volcano.{ext}"),
            name=_nvi_by_name.keys(),
            ext=["pdf", "tsv"],
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_score_density.pdf"),
            name=_nvi_by_name.keys(),
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.bed.gz"),
            name=_nvi_by_name.keys(),
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.deduped.bed.gz"),
            name=_nvi_by_name.keys(),
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.scores_swapped.bed.gz"),
            name=_nvi_by_name.keys(),
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{variant}_summary.pdf"),
            variant=["filtered", "filtered.deduped"],
        ),
        os.path.join(ANALYSIS_DIR, "supplementary_filter_counts.xlsx"),
        os.path.join(ANALYSIS_DIR, "supplementary_filter_counts_deduped.xlsx"),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered_scatter.pdf"),
            name=_nvi_by_name.keys(),
        ),
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.illumina_validation.pdf"),
            name=_nvi_by_name.keys(),
        ),


rule sanitize_bedrmod:
    input:
        lambda wildcards: _raw_input_paths[wildcards.stem],
    output:
        os.path.join(ANALYSIS_DIR, "sanitized", "{stem}.bed"),
    params:
        drop_chroms = " ".join(
            f"--drop-chroms {c}"
            for c in config.get("SANITIZE", {}).get("drop_chroms", [])
        ),
    conda:
        "envs/base.yml"
    shell:
        "python {SCRIPTS_DIR}/sanitize_bedrmod.py {params.drop_chroms} {input} {output}"


rule plot_bedrmod_col_distribution:
    input:
        lambda wildcards: _dist_files[wildcards.stem],
    output:
        tsv = os.path.join(ANALYSIS_DIR, "{stem}.{column}_dist.tsv"),
        pdf = os.path.join(ANALYSIS_DIR, "{stem}.{column}_dist.pdf"),
    params:
        colors = " ".join(
            f"--color '{mod}' '{color}'"
            for mod, color in config["MODIFICATION_COLORS"].items()
        ),
        cov_opts = lambda wildcards: _coverage_dist_opts(wildcards),
    resources:
        mem_mb  = 32 * 1024,
        runtime = 2 * 60,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_bedrmod_col_distribution.py \
            --column     {wildcards.column} \
            {params.colors} \
            {params.cov_opts} \
            --output-tsv {output.tsv} \
            --output-pdf {output.pdf} \
            {input}
        """


rule native_vs_ivt_fisher:
    input:
        native = lambda wildcards: _sanitized(wildcards.name, "native"),
        ivt    = lambda wildcards: _sanitized(wildcards.name, "ivt"),
    output:
        temp(os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.bed")),
    params:
        min_native_cov = lambda wildcards: int(_nvi_by_name[wildcards.name]["min_native_coverage"]),
        min_ivt_cov    = lambda wildcards: int(_nvi_by_name[wildcards.name]["min_ivt_coverage"]),
    resources:
        mem_mb  = 64 * 1024,
        runtime = 8 * 60,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/compare_native_vs_ivt.py \
            --min-native-coverage {params.min_native_cov} \
            --min-ivt-coverage    {params.min_ivt_cov} \
            -o {output} \
            {input.native} \
            {input.ivt}
        """



rule native_vs_ivt_scatter:
    input:
        native = lambda wildcards: _sanitized(wildcards.name, "native"),
        ivt    = lambda wildcards: _sanitized(wildcards.name, "ivt"),
    output:
        pdf = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt.{column}_scatter.pdf"),
        tsv = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt.{column}_scatter.tsv"),
    params:
        min_native_cov = lambda wildcards: int(_nvi_by_name[wildcards.name]["min_native_coverage"]),
        min_ivt_cov    = lambda wildcards: int(_nvi_by_name[wildcards.name]["min_ivt_coverage"]),
    resources:
        mem_mb  = 32 * 1024,
        runtime = 2 * 60,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_native_vs_ivt_scatter.py \
            --column                {wildcards.column} \
            --min-native-coverage   {params.min_native_cov} \
            --min-ivt-coverage      {params.min_ivt_cov} \
            --output-pdf            {output.pdf} \
            --output-tsv            {output.tsv} \
            {input.native} \
            {input.ivt}
        """


rule threshold_sweep:
    input:
        expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.bed.gz"),
            name=_nvi_by_name.keys(),
        ),
    output:
        os.path.join(ANALYSIS_DIR, "threshold_sweep.pdf"),
    params:
        datasets = lambda wildcards, input: " ".join(
            f"--dataset {name} {path}"
            for name, path in zip(_nvi_by_name.keys(), input)
        ),
    resources:
        mem_mb  = 64 * 1024,
        runtime = 2 * 60,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_threshold_sweep.py \
            {params.datasets} \
            --output-pdf {output}
        """


rule pvalue_distribution:
    input:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.bed.gz"),
    output:
        tsv = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_pvalue_dist.tsv"),
        pdf = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_pvalue_dist.pdf"),
    resources:
        mem_mb  = 16 * 1024,
        runtime = 1 * 60,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_pvalue_distribution.py \
            --output-tsv {output.tsv} \
            --output-pdf {output.pdf} \
            {input}
        """


rule volcano_plot:
    input:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.bed.gz"),
    output:
        pdf = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_volcano.pdf"),
        tsv = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_volcano.tsv"),
    params:
        y_cap = config["VOLCANO"]["y_cap"],
    resources:
        mem_mb  = 32 * 1024,
        runtime = 2 * 60,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_volcano.py \
            --y-cap      {params.y_cap} \
            --output-pdf {output.pdf} \
            --output-tsv {output.tsv} \
            {input}
        """


rule score_density:
    input:
        fisher = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.bed.gz"),
        ivt    = lambda wildcards: _sanitized(wildcards.name, "ivt"),
    output:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_score_density.pdf"),
    params:
        sig_padj = config["SCORE_DENSITY"]["sig_padj"],
        colors   = " ".join(
            f"--color '{mod}' '{color}'"
            for mod, color in config["MODIFICATION_COLORS"].items()
        ),
    resources:
        mem_mb  = 32 * 1024,
        runtime = 2 * 60,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_score_density.py \
            --sig-padj   {params.sig_padj} \
            {params.colors} \
            --output-pdf {output} \
            {input.fisher} \
            {input.ivt}
        """


rule plot_filtered_summary:
    input:
        lambda wildcards: expand(
            os.path.join(
                ANALYSIS_DIR,
                "{name}.native_vs_ivt_fisher." + wildcards.variant + ".bed.gz",
            ),
            name=_nvi_by_name.keys(),
        ),
    output:
        os.path.join(ANALYSIS_DIR, "{variant}_summary.pdf"),
    params:
        datasets = lambda wildcards, input: " ".join(
            f"--dataset {name} {path}"
            for name, path in zip(_nvi_by_name.keys(), input)
        ),
        colors = " ".join(
            f"--color '{mod}' '{color}'"
            for mod, color in config["MODIFICATION_COLORS"].items()
        ),
    resources:
        mem_mb  = 32 * 1024,
        runtime = 30,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_filtered_summary.py \
            {params.datasets} \
            {params.colors} \
            --output-pdf {output}
        """


rule filter_sites:
    input:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.bed.gz"),
    output:
        bed    = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.bed"),
        counts = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filter_counts.tsv"),
    params:
        min_log2fc           = lambda wildcards: config["FINAL_FILTER"][wildcards.name]["min_log2fc"],
        max_padj             = lambda wildcards: config["FINAL_FILTER"][wildcards.name]["max_padj"],
        min_ivt_absent_score = lambda wildcards: config["FINAL_FILTER"][wildcards.name]["min_ivt_absent_score"],
        min_native_freq      = lambda wildcards: config["FINAL_FILTER"][wildcards.name]["min_native_freq"],
    resources:
        mem_mb  = 16 * 1024,
        runtime = 30,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/filter_sites.py \
            --min-log2fc           {params.min_log2fc} \
            --max-padj             {params.max_padj} \
            --min-ivt-absent-score {params.min_ivt_absent_score} \
            --min-native-freq      {params.min_native_freq} \
            --output-counts        {output.counts} \
            -o {output.bed} \
            {input}
        """


rule proximity_filter:
    input:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.bed.gz"),
    output:
        bed    = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.deduped.bed"),
        counts = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.dedup_counts.tsv"),
    params:
        max_proximity = lambda wildcards: config["PROXIMITY_FILTER"][wildcards.name]["max_proximity"],
    resources:
        mem_mb  = 4 * 1024,
        runtime = 10,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/proximity_filter.py \
            --max-proximity {params.max_proximity} \
            --output-counts {output.counts} \
            -o {output.bed} \
            {input}
        """


rule swap_scores:
    """Visualisation copy: score <- -log10(padj), original score -> red colour."""
    input:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.bed.gz"),
    output:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.scores_swapped.bed"),
    resources:
        mem_mb  = 8 * 1024,
        runtime = 30,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/swap_scores.py {input} -o {output}
        """


rule plot_filtered_scatter:
    input:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.bed.gz"),
    output:
        os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered_scatter.pdf"),
    params:
        colors = " ".join(
            f"--color '{mod}' '{color}'"
            for mod, color in config["MODIFICATION_COLORS"].items()
        ),
        score_thr      = lambda wildcards: config["FINAL_FILTER"][wildcards.name]["min_ivt_absent_score"],
        log2fc_thr     = lambda wildcards: config["FINAL_FILTER"][wildcards.name]["min_log2fc"],
    resources:
        mem_mb  = 16 * 1024,
        runtime = 30,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_filtered_scatter.py \
            --input              {input} \
            --name               {wildcards.name} \
            --score-threshold    {params.score_thr} \
            --log2fc-threshold   {params.log2fc_thr} \
            {params.colors} \
            --output-pdf         {output}
        """


rule ivt_site_counts:
    """Total IVT sites per modification from the sanitized IVT BED."""
    input:
        lambda wildcards: _sanitized(wildcards.name, "ivt"),
    output:
        os.path.join(ANALYSIS_DIR, "{name}.ivt_counts.tsv"),
    resources:
        mem_mb  = 2 * 1024,
        runtime = 20,
    shell:
        r"""
        ( printf 'modification\tivt_total\n'; \
          awk -F'\t' '!/^#/ && NF > 5 {{ c[$4]++ }} END {{ for (m in c) print m"\t"c[m] }}' {input} \
            | sort -k1,1 ) > {output}
        """


rule supplementary_filter_table:
    input:
        filter_counts = expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filter_counts.tsv"),
            name=_nvi_by_name.keys(),
        ),
        ivt_counts = expand(
            os.path.join(ANALYSIS_DIR, "{name}.ivt_counts.tsv"),
            name=_nvi_by_name.keys(),
        ),
    output:
        os.path.join(ANALYSIS_DIR, "supplementary_filter_counts.xlsx"),
    params:
        datasets = lambda wildcards, input: " ".join(
            f"--dataset {name} {path}"
            for name, path in zip(_nvi_by_name.keys(), input.filter_counts)
        ),
        ivt_datasets = lambda wildcards, input: " ".join(
            f"--ivt-counts {name} {path}"
            for name, path in zip(_nvi_by_name.keys(), input.ivt_counts)
        ),
    resources:
        mem_mb  = 4 * 1024,
        runtime = 10,
    conda: "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/build_filter_table.py \
            {params.datasets} \
            {params.ivt_datasets} \
            -o {output}
        """


rule supplementary_filter_table_deduped:
    input:
        filter_counts = expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filter_counts.tsv"),
            name=_nvi_by_name.keys(),
        ),
        dedup_counts = expand(
            os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.dedup_counts.tsv"),
            name=_nvi_by_name.keys(),
        ),
        ivt_counts = expand(
            os.path.join(ANALYSIS_DIR, "{name}.ivt_counts.tsv"),
            name=_nvi_by_name.keys(),
        ),
    output:
        os.path.join(ANALYSIS_DIR, "supplementary_filter_counts_deduped.xlsx"),
    params:
        datasets = lambda wildcards, input: " ".join(
            f"--dataset {name} {path}"
            for name, path in zip(_nvi_by_name.keys(), input.filter_counts)
        ),
        dedup_datasets = lambda wildcards, input: " ".join(
            f"--dedup-counts {name} {path}"
            for name, path in zip(_nvi_by_name.keys(), input.dedup_counts)
        ),
        ivt_datasets = lambda wildcards, input: " ".join(
            f"--ivt-counts {name} {path}"
            for name, path in zip(_nvi_by_name.keys(), input.ivt_counts)
        ),
    resources:
        mem_mb  = 4 * 1024,
        runtime = 10,
    conda: "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/build_filter_table.py \
            {params.datasets} \
            {params.dedup_datasets} \
            {params.ivt_datasets} \
            -o {output}
        """


rule illumina_validation:
    input:
        unfiltered = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.bed.gz"),
        filtered   = os.path.join(ANALYSIS_DIR, "{name}.native_vs_ivt_fisher.filtered.bed.gz"),
        illumina   = config["ILLUMINA_VALIDATION"]["bed"],
    output:
        os.path.join(ANALYSIS_DIR, "{name}.illumina_validation.pdf"),
    params:
        colors = " ".join(
            f"--color '{mod}' '{color}'"
            for mod, color in config["MODIFICATION_COLORS"].items()
        ),
        min_cov = lambda wildcards: (
            config["NATIVE_VS_IVT"]["data"][
                [r[0] for r in config["NATIVE_VS_IVT"]["data"]].index(wildcards.name)
            ][3]
        ),
    resources:
        mem_mb  = 32 * 1024,
        runtime = 30,
    conda:
        "envs/base.yml"
    shell:
        """
        python {SCRIPTS_DIR}/plot_illumina_validation.py \
            --unfiltered          {input.unfiltered} \
            --filtered            {input.filtered} \
            --illumina            {input.illumina} \
            --name                {wildcards.name} \
            --min-native-coverage {params.min_cov} \
            {params.colors} \
            --output-pdf {output}
        """
